stages:
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

deploy:
  stage: deploy
  image:
    name: docker/compose:latest
  services:
    - docker:dind
  tags:
    - dev
  script:
    - docker stop doc-backend || true
    - docker rm doc-backend || true
    - docker build -t back-image .
    - docker run --name doc-backend -d -p 8080:8080 back-image
